CREATE TABLE `appSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`key` varchar(100) NOT NULL,
	`value` text,
	`description` varchar(255),
	`updatedById` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `appSettings_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
CREATE TABLE `dianCalendar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`obligationCode` varchar(20) NOT NULL,
	`period` varchar(20) NOT NULL,
	`lastDigitNit` varchar(1) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`uploadedById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dianCalendar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `taskAttachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskId` int NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileUrl` text NOT NULL,
	`fileKey` varchar(255) NOT NULL,
	`contentType` varchar(100),
	`fileSize` int,
	`uploadedById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `taskAttachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `clients` ADD `managerId` int;--> statement-breakpoint
ALTER TABLE `tasks` ADD `isAutoGenerated` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `tasks` ADD `taxDeadlineId` int;--> statement-breakpoint
ALTER TABLE `tasks` ADD `evidenceFileUrl` text;--> statement-breakpoint
ALTER TABLE `tasks` ADD `evidenceFileKey` varchar(255);--> statement-breakpoint
ALTER TABLE `tasks` ADD `completionNotes` text;--> statement-breakpoint
ALTER TABLE `users` ADD `username` varchar(64);--> statement-breakpoint
ALTER TABLE `users` ADD `passwordHash` varchar(255);--> statement-breakpoint
ALTER TABLE `users` ADD `cedula` varchar(20);--> statement-breakpoint
ALTER TABLE `users` ADD CONSTRAINT `users_username_unique` UNIQUE(`username`);